In [1]:
import numpy as np
import sys

sys.path.append('../')
import gemstone as gs

In [ ]:
from sklearn.datasets import make_classification

def make_features(n_components=2, n_features=10, n_redundant=0, n_repeated=0, mean_scale=1., variance_scale=1.):
    n_informative = n_features - n_redundant - n_repeated
    means, _ = make_classification(n_components, n_features, n_informative=n_informative, n_redundant=n_redundant, n_repeated=n_repeated, n_classes=n_components, n_clusters_per_class=1, scale=mean_scale)
    variances = variance_scale*np.random.rand(n_features)

    return means, variances

def make_components(n_samples, n_components, n_features, n_redundant=0, n_repeated=0, mean_scale=1., variance_scale=1., bins=None):
    if bins is None:
        pass

# def make(blocks, )

In [6]:
make_features(2, 10)

(array([[-0.19945363,  0.48598009, -0.64642904,  0.44217065,  0.71378866,
          1.25973682,  3.52251204, -0.98101245,  0.70521013,  2.19397689],
        [ 1.67801529,  1.79026681,  1.71087368, -0.69775979,  2.16545177,
          0.9877926 ,  0.76377061, -3.57194736,  2.15993282, -1.07560476]]),
 array([0.82696526, 0.26814194, 0.27058473, 0.13082227, 0.17010357,
        0.5562291 , 0.28049549, 0.48177071, 0.59565585, 0.99045787]))

In [2]:
gs.test()

[[0 0]
 [1 1]]
